eclipse-tractusx/puris

backend/src/main/java/org/eclipse/tractusx/puris/backend/common/api/domain/model/Message.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/api/domain/model/MessageHeader.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/api/domain/model/datatype/DT_RequestStateEnum.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/domain/model/Material.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/domain/model/MaterialPartnerRelation.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/domain/model/Partner.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/domain/repository/MaterialPartnerRelationRepository.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/domain/repository/MaterialRepository.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/dto/MaterialDto.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/dto/PartnerDto.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/MaterialPartnerRelationService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/MaterialPartnerRelationServiceImpl.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/MaterialService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/MaterialServiceImpl.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/PartnerService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/PartnerServiceImpl.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/model/PartnerProductStock.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/model/ProductStock.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/model/ProductStockRequest.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/model/ProductStockRequestForMaterial.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/model/ProductStockResponse.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/model/Stock.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/repository/MaterialStockRepository.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/repository/PartnerProductStockRepository.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/repository/ProductStockRepository.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/repository/ProductStockRequestRepository.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/repository/ProductStockResponseRepository.java

Currently the relationship of the material and partner were not correctly mapped according to m:n scenarios based on one material having e.g. multiple suppliers each with a different supplier number.
This commit handles the domain section (model + repositories) and the corresponding logic layer.

feat: added MaterialPartnerRelation and accompanying services

---

.github/workflows/build-image-backend.yml
.github/workflows/build-image-frontend.yml

I added two workflows for github to publish images to docker hub. There is one workflow for the frontend and one for the backend that will be pulled automatically.
Uses, same as the example, following actions:
- [build-and-push](https://github.com/docker/build-push-action)
- [Dockerhub description](https://github.com/peter-evans/dockerhub-description) update using README.md
This should trigger automatic builds with labels for nearly all git refs that are merged on main, except for the PR.

CI: added workflow for docker hub publishing TRG 4.05

---

.github/workflows/veracode-backend.yml
.github/workflows/veracode-frontend.yml

This pull request updates the Veracode GitHub action to only run in the upstream `eclipse-tractusx/puris` repository, since it fails on forks due to missing secrets.

ci(veracode): prevent veracode GitHub action to run on forks

---

.github/workflows/render-puml-to-svg.yml

Fixes a file extension mistake in the puml to svg workflow.

ci: fix render puml to svg workflow

---

.github/workflows/trivy.yml

https://github.com/eclipse-tractusx/sig-security/issues/25
Setup trivy scans.
You don't need the trivy config scan - kics does this job.
I configured for you the trivy container scans for your frontend and backend.
In future, please add the `latest` tag to your published images and configure the `latest` tag in the trivy workflow config.

ci: configure trivy scans

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/AssetCreatorCommandLineRunner.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/controller/EdcController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/service/EdcAdapterService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/service/ExternalConnectorService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/util/EdcRequestBodyBuilder.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/logic/service/ProductStockRequestApiServiceImpl.java

Several renamings as requested in issue #101 , solving that issue. 

refactor: update naming conventions in EDC classes

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/controller/MaterialController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/controller/PartnerController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/controller/StockViewController.java

We introduced site information with PR #27 and increased validations in the past time. We've not yet been adding those capabilities to the frontend (see issue #112). 
Removed CrossOrigin annotations in controller, as I seem to have missed them in the TLS PR (#117).
This PR prepares the frontend to get the remaining data (own sites and addresses) to create dropdowns in the frontend.

Feat: add route to partner controller endpoint to receive site and address information of the own application

---

backend/src/test/java/org/eclipse/tractusx/puris/backend/stock/controller/StockViewControllerTest.java
frontend/src/views/StockView.vue
frontend/src/views/stock/PartnerStockSFC.vue
frontend/src/views/stock/StockTableSFC.vue

This PR prepares the StockView to process Order Position References. It adds three new fields with no further handling:
- customer order number
- customer order position number
- supplier order number

Feat: add order position reference to stockview

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/common/security/logic/ApiKeyAuthenticationProvider.java

Removed unnecessary success log.

chore: Removed unnecessary success log

---

local/tractus-x-edc/config/customer/puris-backend.properties

- fixed typo ("crednetials" vs "credentials")

Fix: typo in customer backend properties

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/util/EdcRequestBodyBuilder.java

- The method that creates request bodies for the puris api assets didn't properly set the URL for the status request api asset

Fix: missing statusrequest url

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/common/security/SecurityConfig.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/security/logic/ApiKeyAuthenticationFilter.java

The Swagger UI was unusable because the API Key has not been configured to be used globally. Now it is.

feat(SecurityConfig): configure Swagger API-Key usage globally

---

frontend/Dockerfile

When checking the #255 the nginx.conf substitution for rate limitting had problems due to permissions.
Tested together with @f-zimmer. Problem did not occure anymore but we wanted to make sure it works with 777 rights instead of 117.

fix(frontend/Dockerfile): enhanced permissions for nginx.conf substitution

---

README.md
backend/README.md
frontend/Dockerfile
frontend/README.md

Move from stable-alpine to common alpine image as stated in TRG 4.06. Also updated docker notice.
Added Healthcheck for Frontend Dockerfile
Updated Docker Notices / Readmes

ci(frontend/Dockerfile): change from stable-alpine to alpine for nginx

---

.github/workflows/build-image-backend.yml
.github/workflows/build-image-frontend.yml
README.md
backend/DOCKER_NOTICE.md
backend/README.md
frontend/DOCKER_NOTICE.md
frontend/README.md

chore: extracted docker notice to separate files (TRG 4.06)

---

frontend/Dockerfile
frontend/start-nginx.sh

Per [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) no additional packages should be installed. @tomaszbarwicki provided workaround ideas that have been incorporated.

ci(frontend/Dockerfile): removed sponge from base image

---

CHANGELOG.md
DEPENDENCIES_BACKEND
backend/DEPENDENCIES

PURIS FOSS is currently not compliant to the CX Styleguide (see [comment](https://github.com/eclipse-tractusx/sig-release/issues/510#issuecomment-1964360137)). Added this information to changelog

chore: add ux styleguide incompatiblity to known knowns

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/common/ddtr/logic/util/DtrRequestBodyBuilder.java
local/docker-compose-infrastructure.yaml

- updated MIW docker image in local deployment to 0.4.0, solving #186 
- adjusted logging output in DtrRequestBodyBuilder to "debug" level

Feat: updated miw to 0.4.0

---

frontend/src/components/TableWithRowHeader.tsx
frontend/src/features/dashboard/components/Dashboard.tsx
frontend/src/features/dashboard/components/DashboardFilters.tsx
frontend/src/features/dashboard/components/DeliveryInformationModal.tsx
frontend/src/features/dashboard/components/DemandTable.tsx
frontend/src/features/dashboard/components/ProductionTable.tsx
frontend/src/features/dashboard/util/helpers.tsx
frontend/src/features/dashboard/util/table-helpers.tsx
frontend/src/index.css
frontend/src/models/types/data/delivery.ts
frontend/src/views/SupplierDashboardView.tsx

- implements #211 
- new layout to include future support for ShortTermMaterialDemand, DeliveryInformation and PlannedProductionOutput
- support for multi-sourcing and multi-customer views

feat(supplier-dashboard): new dashboard layout

---

CHANGELOG.md

chore: include feedback from ui to known knows

---

frontend/package.json

Forgot to increase frontend version for release

chore(package.json): increase frontend version for patch release

---

.act/pr_event.json
.github/pull_request_template.md
.github/workflows/build-image-backend.yml
.github/workflows/build-image-frontend.yml
.github/workflows/codeql.yml
.github/workflows/helm-test.yml
.github/workflows/kics.yml
docs/DEVELOPMENT.md

We currently do not always release every change in the helm chart. Thus increasing the version leads to confusion.
As a result I updated the workflow to
- exclude version check as a failure reason during lint
- in the end perform version check to fail (reminder to check on what to do)

Ci(helm-test): don't fail on chart version check failure

---

CONTRIBUTING.md
LICENSE_non_code
NOTICE.md
backend/NOTICE.md

- inserted the requested changes as demanded in #430 
- does not fully solve the above mentioned issue, since there are still open questions, which are currently unanwered

Chore: Mandatory change in licensing

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/MaterialPartnerRelationServiceImpl.java

- i noticed that when the triggerPartTypeRetrievalTask method is called, there is currently no mechanism to make sure that a cx id that was fetched as a result of that method call is immediately published to the respective shell descriptor at the DTR. 
- the fix for this is to initiate a DtrRegistration Task instead of just a PartTypeInformationRetrievalTask. A DtrRegistrationTask will always trigger a PartTypeInformationRetrievalTask when it notices that there is a missing CX id from a supplier partner. But beyond that it will also send an update for the approriate shell descriptor to the DTR

Fix: Publishing cxId to DTR

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/erpadapter/domain/model/ErpAdapterTriggerDataset.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/erpadapter/logic/service/ErpAdapterTriggerService.java

- there is a potential case, that the most recent information can get lost, if a scheduled erp adapter request and a call to the notifyPartnerRequest are happening at nearly the same time
- provided a fix for this

fix: potential information loss

---

README.md
local/docker-compose.yaml

chore: bump dtr version from 0.4.3 to 0.5.0

---

README.md
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/service/EdcAdapterService.java
local/tractus-x-edc/config/customer/data-plane.properties
local/tractus-x-edc/config/supplier/data-plane.properties
local/tractus-x-edc/docker-compose.yaml

- local docker deployment uses TX-EDC version 0.7.3
- EdcAdapterService now calls 'v3' management api endpoints on control-plane

chore: update tx-edc 0.7.3

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/controller/DeliveryController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/controller/DeliveryRequestApiController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/demand/controller/DemandController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/demand/controller/DemandRequestApiController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/demandandcapacitynotification/controller/DemandAndCapacityNotificationController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/demandandcapacitynotification/controller/DemandAndCapacityNotificationRequestApiController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/controller/MaterialController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/controller/PartTypeInformationController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/controller/PartnerController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/production/controller/ProductionController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/production/controller/ProductionRequestApiController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/controller/ItemStockRequestApiController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/controller/StockViewController.java

- made edits to various rest controller classes, where the current swagger ui was indicating a response body in error cases
- some minor inconsistency fixes
- solves #515 

fix: swagger_ui inconsistencies

---

.github/workflows/trufflehog.yml
docs/DEVELOPMENT.md

fix(trufflehog): checkout forks during pr

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/service/EdcAdapterService.java

-  added handling for 409 responses on asset registration
- solves #525 

feat: added handling for 409 responses on asset registration

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/controller/PartnerController.java

- added filter to exclude own partner entity from output in GET partner/all endpoint
- solves #524 
- solves #423 

fix: remove own partner from partner/all endpoint

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/demandandcapacitynotification/logic/adapter/DemandAndCapacityNotificationSammMapper.java
backend/src/test/java/org/eclipse/tractusx/puris/backend/demandandcapacitynotification/logic/adapter/DemandAndCapacityNotificationSammMapperTest.java

- fixed/improved DemandAndCapacitySammMapper: 
- now properly distinguishes between Samms that came from a supplier or a customer, when identifying the affected materials
- now using customermaterialnumber / suppliermaterialnumber fields in the samm/json payload
- added unit tests for samm mapper
- solves #465 

feat: demand and capacity notification improvements

---

.github/workflows/unit-test-backend.yaml

To ensure we don't miss existing unit tests during update, I added a workflow to run unit tests in the backend during PR.
Will undo making one test fail after functional review.

ci: add workflow for backend unit tests

---

backend/src/main/java/org/eclipse/tractusx/puris/backend/common/ddtr/logic/util/DtrRequestBodyBuilder.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/domain/model/AssetType.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/domain/model/DaysOfSupplyContractMapping.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/domain/repository/DaysOfSupplyContractMappingRepository.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/service/EdcAdapterService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/service/EdcContractMappingService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/util/VariablesService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/demand/controller/DemandController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/demand/logic/services/DemandRequestApiService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/demand/logic/services/DemandService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/demand/logic/services/OwnDemandService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/controller/DaysOfSupplyRequestApiController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/controller/SupplyController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/domain/repository/ReportedSupplierSupplyRepository.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/adapter/DaysOfSupplySammMapper.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/dto/daysofsupplysamm/AllocatedDaysOfSupply.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/dto/daysofsupplysamm/DaysOfSupply.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/dto/daysofsupplysamm/QuantityOfDaysOfSupply.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/service/CustomerSupplyService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/service/DaysOfSupplyRequestApiService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/service/SupplierSupplyService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/service/SupplyService.java
backend/src/main/resources/application.properties
backend/src/test/resources/application.properties
charts/puris/Chart.yaml
charts/puris/templates/backend-deployment.yaml
charts/puris/values.yaml
local/tractus-x-edc/config/customer/puris-backend.properties
local/tractus-x-edc/config/supplier/puris-backend.properties

- add SAMM models for Days of Supply
- implemented logic for registering the corresponding Assets and Contract
- implemented the request service for exchanging Days of Supply through the EDC
reolves #312 

feat: implemented days of supply edc integration

---

.github/workflows/helm-test.yml
.github/workflows/trivy.yml
CHANGELOG.md
README.md
backend/DOCKER_NOTICE.md
backend/pom.xml
charts/puris/Chart.yaml
charts/puris/README.md
charts/puris/values.yaml
docs/admin/Admin_Guide.md
docs/api/openAPI.yaml
frontend/DOCKER_NOTICE.md
frontend/package.json

This PR is meant to cover last changes needed for R25.03 as noticed during Quality Gate Check #785.
Changes:
- wrote changelog for app version 3.0.0
- set versions in frontend, backend, charts and associated documentation
- exported openApi updates for [TRG 1.08](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-08)
- updated documentation for administration and standard values in chart
- updated docker_notice files to include more information as mentioned in [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06)
- CI
- bump standard versions in helm-test
- fix trivy to only run on eclipse-tractusx/puris

docs: prepare release 25.03

---

CHANGELOG.md
frontend/src/features/material-details/components/PlannedProductionModal.tsx

- added missing mandatory indicator on Estimated Completion Time
resolves #799

fix: mandatory indicator for estimated completion time

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/puris/backend/DataInjectionCommandLineRunner.java
charts/puris/README.md
charts/puris/templates/backend-deployment.yaml
charts/puris/values.yaml

The ddl-auto setting has not been passed through correctly. In combination with the default value a helm upgrade or a pod restart wiped all data in the database.
Changes:
- passthrough full property (`spring.jpa.hibernate.ddl-auto` - spring has been missing)
- update ddl-auto standard value
- updated changelog
- updated creation of own partner entity which caused in an exception when partner with own bpnl already existed. 
> Note: helm chart has not been bumped because a minor change has been entered but not been released.

fix(helm): passthrough jpa.hibernate.ddl-auto

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/ddtr/logic/DtrAdapterService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/ddtr/logic/util/DtrRequestBodyBuilder.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/domain/model/AssetType.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/service/EdcAdapterService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/controller/DeliveryRequestApiController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/demand/controller/DemandRequestApiController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/erpadapter/logic/service/ErpAdapterTriggerService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/controller/PartTypeInformationController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/production/controller/ProductionRequestApiController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/controller/ItemStockRequestApiController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/controller/DaysOfSupplyRequestApiController.java
backend/src/test/java/org/eclipse/tractusx/puris/backend/common/ddtr/logic/util/DtrRequestBodyBuilderTest.java
backend/src/test/java/org/eclipse/tractusx/puris/backend/erpadapter/logic/service/ErpAdapterRequestValidationTest.java
docs/DEVELOPMENT.md

solves #844 #846 #841 
Adds a test for the shell and submodel composure.
I also noticed that we created to ExternalSubjectIds, but not the tenantId when creating / updating ShellDescriptors in our DTR. Thus, I changed that behavior.

Fix: expose and contract submodels following CX-0002

---

local/testing/TESTING.md
local/testing/e2e/cypress.config.js
local/testing/e2e/cypress.env.json
local/testing/e2e/cypress/e2e/general/navigation.spec.cy.js
local/testing/e2e/cypress/e2e/general/sidebar.spec.cy.js
local/testing/e2e/cypress/support/commands.js
local/testing/e2e/docker-compose-e2e.yaml

feat: implemented login logic for cypress tests

---

CHANGELOG.md
DEPENDENCIES_BACKEND
backend/pom.xml

- bump spring boot to version 3.4.5 to address [CVE-2025-31650](https://www.cve.org/CVERecord?id=CVE-2025-31650)

chore: bump spring boot version to fix security vulnerabilities

---

CHANGELOG.md
backend/src/test/java/org/eclipse/tractusx/puris/backend/supply/logic/SupplyServiceTest.java

- extended days of supply unit tests:
- test for insufficient number of days
- initial stock of 0
- mixed own and reported deliveries 

feat: extended days of supply unit tests with edge cases

---

charts/puris/Chart.yaml
charts/puris/templates/_helpers.tpl

This PR introduces the ability to change the pod names via the frontend.nameOverride and backend.nameOverride values.
Changes to logic behind the backend.name and frontend.name values to fix the nameOverride (if release name is puris):
- `--set frontend.nameOverride=newFrontendName` results in `puris-newFrontendName-frontend`
- `--set backend.nameOverride=newBackendName` results in `puris-newBackendName-frontend`
Note: changes also the default pods names from
- `backend` to `puris-backend`
- `--set backend.nameOverride=""` results in `puris-backend`
- `frontend` to `puris-frontend`
- `--set frontend.nameOverride=""` results in  `puris-frontend`
Yes, the nameOverride was mentioned in the values.yml file but didn't result in a name change.
Please ensure to do as many of the following checks …

fix helm chart: not working frontend and backend nameOverride

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/MaterialRefreshService.java

- fixed a mistake in the material refresh logic that resulted in sending the wrong refresh request to customers
fixes #879 

fix: changed the material refresh logic to request the correct stock

---

.act/workflow_dispatch_helm_test.json
.github/workflows/helm-test.yml
.github/workflows/unit-test-backend.yaml
CHANGELOG.md
backend/pom.xml
charts/puris/Chart.yaml
charts/puris/README.md
charts/puris/templates/3.0.0-nameOverride-hook.yaml
charts/puris/templates/_helpers.tpl
charts/puris/templates/backend-deployment.yaml
charts/puris/templates/frontend-deployment.yaml
charts/puris/templates/migration/3.0.0/nameOverride-cleanup-batch.yaml
charts/puris/templates/migration/3.0.0/nameOverride-hook.yaml
charts/puris/templates/migration/3.0.0/nameOverride-role.yaml
charts/puris/templates/migration/3.0.0/nameOverride-rolebinding.yaml
charts/puris/templates/migration/3.0.0/nameOverride-serviceaccount.yaml
charts/puris/values.yaml
docs/DEVELOPMENT.md
docs/README.md
docs/admin/Migration_Guide.md

solves #885, #886, #887
Additionally I
- improved stability for dashtool usage in backend (don't run during backend test, use batches to overcome timeouts)
- added the migration guide for #882   

fix(chart): harmonize protocol usage in urls

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/controller/EdcController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/security/SecurityConfig.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/security/domain/ApiKeyAuthentication.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/security/logic/ApiKeyAuthenticationFilter.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/common/security/logic/KeycloakJwtAuthenticationConverter.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/file/controller/FileController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/controller/MaterialController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/controller/MaterialPartnerRelationsController.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/controller/PartnerController.java
docs/admin/Admin_Guide.md

- added role-based permission handling
- added swagger annotations for admin routes
resolves #904 

feat: add role-based permission handling

---

CHANGELOG.md
docs/api/openAPI.yaml

- updated openAPI docs for the changes in R25.09
resolves #923 

chore: update open api docs

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/puris/backend/demandandcapacitynotification/logic/service/OwnDemandAndCapacityNotificationService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/demandandcapacitynotification/logic/service/ReportedDemandAndCapacityNotificationService.java
frontend/src/components/ui/DateTime.tsx
frontend/src/features/notifications/components/CollapsibleNotification.tsx
frontend/src/features/notifications/components/NotificationInformationModal.tsx
frontend/src/features/notifications/components/NotificationResolutionMessageModal.tsx
frontend/src/index.css
frontend/src/models/types/data/demand-capacity-notification.ts
frontend/src/services/demand-capacity-notification.ts
frontend/src/views/DemandCapacityNotificationView.tsx

- Update notification following standard version 3
- Implemented forwarding, updating, resolving notifications
- Adjusted design of the page
Resolves #918 

feat: update notification frontend

---

CHANGELOG.md
frontend/src/features/notifications/components/NotificationInformationModal.tsx
frontend/src/features/notifications/components/NotificationResolutionMessageModal.tsx
frontend/src/models/types/data/demand-capacity-notification.ts

- Fixed issue of not being able to resolve notification due to an empty text
- Added validation checks against only white spaces in both text and resolution message
Solves issue: #950 

Notification resolution bug

---

CHANGELOG.md
README.md
local/docker-compose.yaml

- bump DTR version to 0.9.0-RC1

chore: bump dtr to version 0.9.0-rc1

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/puris/backend/file/logic/service/ExcelService.java
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/model/ItemStock.java

- fixed a bug that prevents documents from being uploaded if a previously filled row is emptied (but not deleted)
- updated the `equals` method for item stock to consider stocks as inequal if the `isBlocked` value is different 

fix: excel import validations

---

CHANGELOG.md
backend/pom.xml
backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/controller/StockViewController.java
charts/puris/Chart.yaml
charts/puris/README.md
docs/admin/Migration_Guide.md
docs/api/openAPI.yaml
frontend/package-lock.json
frontend/package.json
frontend/src/features/material-details/hooks/useMaterialDetails.ts
frontend/src/features/stock-view/hooks/useStocks.ts
local/bruno/puris-integration-test/Test_01-MAD/01_02-Operational Data/Customer/Stock/Get Semiconductor Material Stock.bru
local/bruno/puris-integration-test/Test_01-MAD/01_02-Operational Data/Supplier/Stock/Get Semiconductor Product Stocks.bru

- added `ownMaterialNumber` parameter to `stockView/material-stocks` and `stockView/product-stocks`
- added `ownMaterialNumber` parameter to `useStocks` hook
- adjusted bruno requests to accommodate the change
resolves #979 

fix: stocks always including values for all materials
