- .github/workflows/render-puml-to-svg.yml
Added manual trigger for plant uml workflow
> ci: Add manual trigger to render-puml-to-svg.yml

- .github/workflows/chart-release.yaml
solves #73 
I only wanted the manual flow and don't release on each change on main.
> CI: added helm releaser action

- backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/model/measurement/MeasurementUnit.java
Seven units have been later on added to the shared quantity model. Thus, I added them to the backend.
> feat: added further units that have been added based on shared quantity model

- backend/src/main/java/org/eclipse/tractusx/puris/backend/PurisApplication.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/service/EdcAdapterService.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/util/EdcRequestBodyBuilder.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/PartnerService.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/PartnerServiceImpl.java
- removed unrestricted policies and contract definitions
- added feature to create BPNL specific policy/contract defintions on creation of a new partner entity, solves #136
> feat: added bpnl specific policies and contract defintions

- backend/src/main/java/org/eclipse/tractusx/puris/backend/common/api/logic/service/PatternStore.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/controller/StockViewController.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/logic/dto/StockDto.java
- frontend/src/views/StockView.vue
> fix(StockView): enabled 'Allocated to Partner *' field while radio button 'Product' is clicked

- backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/controller/EdcController.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/service/EdcAdapterService.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/util/EdcRequestBodyBuilder.java
- frontend/src/views/TransferView.vue
- added request methods for transfers and contractagreement to EdcAdapterService
- added endpoint to EdcController
- updated frontend TransferView.vue for current backend api and control plane data structure, solving #133 
> feat: update TransferView

- frontend/src/views/stock/PartnerStockSFC.vue
Removed display of duplicate entries for partner stocks.
> fix: Removed display of duplicate entries for partner stocks.

- frontend/src/views/StockView.vue
- frontend/src/views/SupplierDashboard.vue
Added conficential notice banner to Stock View and Supplier Dashboard
> feat: Added conficential notice banner to Stock View and Supplier Dashboard

- CHANGELOG.md
- backend/pom.xml
- charts/puris/Chart.yaml
- frontend/package-lock.json
- frontend/package.json
- frontend/src/assets/aboutPage.json
initial release of puris foss
- Updated versions to 1.0.0
- updated frontend about license information
- updated changelog
> Release 1.0.0

- .github/workflows/build-image-backend.yml
- .github/workflows/build-image-frontend.yml
Updated the workflow pattern for tags to only run for tags starting with numbers in semver.
> ci(docker): updated workflow to match on pattern starting with numbers

- .github/workflows/helm-test.yml
closes #276 
Note: in [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) it's indicated that we use first tractusx-dev[CHART] -> I expected it to be a typo and used charts/[CHART]
> ci(helm-test): add upgrade check

- DEPENDENCIES_BACKEND
- backend/DEPENDENCIES
- backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/logic/adapter/ItemStockSammMapper.java
- backend/src/test/java/org/eclipse/tractusx/puris/backend/stock/logic/adapter/ItemStockSammMapperTest.java
- fixed deserialization logic in itemstockSammMapper
> Fix: samm mapping logic

- DEPENDENCIES_FRONTEND
- backend/src/main/java/org/eclipse/tractusx/puris/backend/common/ddtr/logic/util/DtrRequestBodyBuilder.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/common/security/SecurityConfig.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/controller/DeliveryController.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/controller/DeliveryRequestApiController.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/domain/model/DeliveryResponsibilityEnumeration.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/domain/model/IncotermEnumeration.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/adapter/DeliveryInformationSammMapper.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/dto/DeliveryDto.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/dto/deliverysamm/Delivery.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/dto/deliverysamm/DeliveryInformation.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/dto/deliverysamm/Location.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/dto/deliverysamm/OrderPositionReference.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/dto/deliverysamm/Position.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/dto/deliverysamm/TransitEvent.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/dto/deliverysamm/TransitLocations.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/service/DeliveryRequestApiService.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/service/OwnDeliveryService.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/service/ReportedDeliveryService.java
- frontend/DEPENDENCIES
- created SAMM models for Delivery Information 2.0.0
- implemented the EDC data exchange flow for Delivery Information
resolves #198 
> feat: implemented delivery information edc flow

- .github/workflows/build-image-frontend.yml
- frontend/src/assets/aboutPage.json
….sh and use tree for source
resolves #404 
notice file has been incompletely substituted
- added github environment variables
- replaced blob by tree for source url
Thanks @evegufy for your support! :)
> fix(build-image-frontend): add environment variables for legal-notice

- backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/service/EdcAdapterService.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/util/EdcRequestBodyBuilder.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/common/util/VariablesService.java
- backend/src/test/java/org/eclipse/tractusx/puris/backend/common/edc/logic/service/EdcAdapterServiceTest.java
resolves #407 
pair programmed code with @eschrewe and added some tests
> Fix: enhance constraint check for consumer

- CHANGELOG.md
- docs/user/User_Guide.md
- frontend/src/components/layout/Footer.tsx
- frontend/src/components/layout/SideBar.tsx
- frontend/src/components/ui/DateTime.tsx
- frontend/src/components/ui/LabelledAutoComplete.tsx
- frontend/src/contexts/authContext.tsx
- frontend/src/features/dashboard/components/DashboardFilters.tsx
- frontend/src/features/dashboard/components/DeliveryInformationModal.tsx
- frontend/src/features/dashboard/components/DemandCategoryModal.tsx
- frontend/src/features/dashboard/components/PlannedProductionModal.tsx
- frontend/src/features/stock-view/components/StockDetailsView.tsx
- frontend/src/features/stock-view/components/StockUpdateForm.tsx
- frontend/src/hooks/useFetch.ts
- frontend/src/index.css
- frontend/src/services/authentication-service.ts
- frontend/src/views/CatalogView.tsx
- frontend/src/views/DashboardView.tsx
- frontend/src/views/NegotiationView.tsx
- frontend/src/views/StockView.tsx
- frontend/src/views/TransferView.tsx
- Updated frontend to be more in line with the Catena-X style guide
> feat: update frontend to be in line with catena-x style guide

- .github/workflows/build-image-backend.yml
- .github/workflows/build-image-frontend.yml
- backend/Dockerfile
- frontend/Dockerfile
- added copy commands to dockerfiles and github workflows
> chore: copy new license file

- backend/src/main/java/org/eclipse/tractusx/puris/backend/demandandcapacitynotification/controller/DemandAndCapacityNotificationRequestApiController.java
- added full sample request for demandandcapacitynotification request endpoint
- solves #487 
> fix: demandandcapacitynotification_swaggerui

- backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/controller/MaterialPartnerRelationsController.java
- added missing decoding
- added error handling for input data without proper base64 encoding
- solves: #579 
> fix: missing base64 decoding in mpr controller

- local/bruno/puris-integration-test/Test_01-MAD/01_01-Init/Customer/MAD/Create Control Unit Product.bru
- local/bruno/puris-integration-test/Test_01-MAD/01_01-Init/Customer/MAD/Create Semiconductor Material.bru
- local/bruno/puris-integration-test/Test_01-MAD/01_01-Init/Customer/MAD/Get All Partners.bru
- local/bruno/puris-integration-test/Test_03-DTR/Check Customer DTR/Query dtr for ShellDescriptor Customer.bru
- local/postman/puris-integration-test.postman_collection.json
> fix: integration test suites (#687)

- DEPENDENCIES_BACKEND
- frontend/src/components/layout/Layout.tsx
- frontend/src/components/layout/SideBar.tsx
- frontend/src/components/ui/GridItem.tsx
- frontend/src/contexts/dataModalContext.tsx
- frontend/src/contexts/notificationContext.tsx
- frontend/src/features/dashboard/components/Dashboard.tsx
- frontend/src/features/dashboard/components/DeliveryInformationModal.tsx
- frontend/src/features/dashboard/components/DemandCategoryModal.tsx
- frontend/src/features/dashboard/components/PlannedProductionModal.tsx
- frontend/src/features/dashboard/hooks/useDelivery.ts
- frontend/src/features/dashboard/hooks/useDemand.ts
- frontend/src/features/dashboard/hooks/useProduction.ts
- frontend/src/features/material-details/util/helpers.tsx
- frontend/src/features/notifications/components/NotificationInformationModal.tsx
- frontend/src/features/stock-view/components/StockDetailsView.tsx
- frontend/src/features/stock-view/hooks/useReportedStocks.ts
- frontend/src/hooks/useFetch.ts
- frontend/src/index.css
- frontend/src/main.tsx
- frontend/src/models/types/data/production.ts
- frontend/src/models/types/data/stock.ts
- frontend/src/router.tsx
- frontend/src/theme.tsx
- frontend/src/util/helpers.ts
- frontend/src/views/DemandCapacityNotificationView.tsx
- reworked the modal logic in preparation for #737 
> feat: modal-rework

- charts/puris/Chart.yaml
- charts/puris/README.md
- charts/puris/templates/backend-secrets.yaml
- charts/puris/values.yaml
> fix(charts/puris): use correct auth-secret also in values

- local/testing/e2e/cypress/e2e/customer/material-details-view-data-operations.spec.cy.js
- local/testing/e2e/cypress/e2e/customer/material-list-view.spec.cy.js
- local/testing/e2e/cypress/e2e/general/sidebar.spec.cy.js
- local/testing/e2e/cypress/e2e/supplier/material-details-view-data-operations.spec.cy.js
- fixed an issue in the sidebar tests
- added timeouts and addional checks to improve the reliability of tests
> fix: improved robustness of automated end-to-end tests

- CHANGELOG.md
- local/testing/e2e/cypress/e2e/customer/material-details-view-data-display.spec.cy.js
- local/testing/e2e/cypress/e2e/customer/material-details-view-data-operations.spec.cy.js
- local/testing/e2e/cypress/e2e/customer/material-list-view.spec.cy.js
- local/testing/e2e/cypress/e2e/general/navigation.spec.cy.js
- local/testing/e2e/cypress/e2e/general/sidebar.spec.cy.js
- local/testing/e2e/cypress/e2e/supplier/material-details-view-data-operations.spec.cy.js
- local/testing/e2e/cypress/support/commands.js
- added missing role (customer or supplier) to the login functions within customer and supplier test specs
> fix: add role to cypress login

- CHANGELOG.md
- backend/src/main/java/org/eclipse/tractusx/puris/backend/file/logic/service/ExcelService.java
- backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/domain/model/ItemStock.java
- backend/src/test/java/org/eclipse/tractusx/puris/backend/file/logic/services/ExcelServiceTest.java
- created comprehensive unit tests for the excel import api
resolves #910 
> feat: added unit test for excel service

- CHANGELOG.md
- DEPENDENCIES_BACKEND
- backend/pom.xml
- local/.gitignore
- local/DEPENDENCIES_BRUNO_CLI
- local/package-lock.json
- updated backend and bruno dependencies to fix high and critical severity vulnerabilities
> chore: update dependencies
